### ISSUE TITLE
Issues Creating Game

### ISSUE THREAD

**Issue by samuelsmithhk** [yoav-zibin/GameBuilder#18]
**As a** game designer
**I would** like to submit a game spec
**But** an issue within the GameBuilder is preventing me from uploading my spec.

**Steps to reproduce**:
1. Create a new spec
2. Select game board "roulette_board.001"
3. Place elements "roulette-wheel" onto spec, as well as 10 * the following elements:
 - roulette-chip-100
 - roulette-chip-50
 - roulette-chip-25
 - roulette-chip-10
 - roulette-chip-5
 - roulette-chip-1
4. set the wikipedia link to https://en.wikipedia.org/wiki/Roulette
6. set the game icon to roulette_wheel.024
6. set the spec title to "roulette"
7. try to submit.

**What is supposed to happen**
The spec should be successfully loaded into firebase

**What actually happens**
The UI presents with a simple error message, "unable to load spec"
Looking into console logs, it is a permission denied error - usually the result of some part of the request not adhering to one of the firebase rules.

**Comment by samuelsmithhk** [comment]
<img width="985" alt="screen shot 2017-12-06 at 22 59 16" src="https://user-images.githubusercontent.com/9402447/33698228-28a91c06-dad9-11e7-8643-9cd0d243e6ea.png">

<img width="1430" alt="screen shot 2017-12-06 at 22 59 31" src="https://user-images.githubusercontent.com/9402447/33698231-31526510-dad9-11e7-964a-8c3518e020a2.png">

**Comment by apsdehal** [comment]
Closing as fixed.
